### ISSUE TITLE
Описать модель данных проекта в документации Core API

### ISSUE THREAD

**Issue by emberati** [pixplaze/pixplaze-docs#12]
Модель данных проекта содержит список моделей данных серверов.
Проект* - совокупность серверов.

Поля:
- название проекта
- описание проекта
- список тэгов сервера
- список серверов проекта (thumbnail изображение сервера, порт карты, порт API берутся из сервера, который указан как `primary`)

**Comment by pazik98** [comment]
А почему это должно быть в Core API? Почему сервер вообще должен знать о проекте?

**Comment by emberati** [comment]
Временное решение, эта структура должна быть переносима на бэк
